config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get '/team', to: 'static_pages#team'

  get '/contact', to: 'static_pages#contact'
  
  get '/welcome/:id', to: 'static_pages#welcome_user'

  post '/', to: 'static_pages#welcome_id', as: 'welcome'
  
  get '/gossip/:gossip_id', to: 'static_pages#gossip_id', as: 'gossip'

  get '/user/:user_id', to: 'static_pages#user_id', as: 'user'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  belongs_to :tag, optional: true
  has_many :likes
  has_many :comments, as: :comment_type
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :gossip, optional: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossips
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city, optional: true
  has_many :gossips
  has_many :likes
  has_many :comments, as: :comment_type
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
    @gossips = Gossip.all
  end

  def welcome_user
    @gossips = Gossip.all
  end

  def gossip_id
    @gossip = Gossip.find(params["gossip_id"])
    @user = User.all
  end

  def user_id
    @user = User.find(params["user_id"])
  end

end


#     @user = User.new
#     @user.first_name = params["first_name"]
#     @user.save
#     puts "$" * 60 #ça affiche une ligne de 60 symboles $ facilement visible dans le terminal
#     puts @user.first_name #tu sais que params doit s'afficher entre les 2
#     puts "$" * 60

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
 <head>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">

   <title>TheGossipProject</title>
   <%= csrf_meta_tags %>
   <%= csp_meta_tag %>

   <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <header class="d-flex justify-content-center py-3">
      <ul class="nav nav-pills">
        <li class="nav-item"><%= link_to "Home", root_path, class: "nav-link active"%></li>
        <li class="nav-item"><%= link_to "Team", team_path, class: "nav-link"%></li>
        <li class="nav-item"><%= link_to "Contact", contact_path, class: "nav-link"%></li>
      </ul>
    </header>

 </head>

 <body>
   <%= yield %>


 </body>

</html>

app/views/static_pages/contact.html.erb
<h6>Nous contactes pas stp</h6>

app/views/static_pages/gossip_id.html.erb
<html lang="en"><head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.83.1">
    <title>Heroes · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/heroes/">

    

    <!-- Bootstrap core CSS -->
<link href="/docs/5.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#7952b3">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="heroes.css" rel="stylesheet">
  </head>
  <body>
    
<main>
  <h1 class="visually-hidden">Heroes examples</h1>

  <div class="px-4 py-5 my-5 text-center">
    <h1 class="display-5 fw-bold">Hello , voici le gossip numéro <%= params["gossip_id"] %>  ! </h1>
    <div class="col-lg-6 mx-auto">
      <p class="lead mb-4">Son titre: <%= @gossip.title %></p>
      <p class="lead mb-4">Son auteur : <%= link_to @gossip.user.first_name, user_path(@gossip.user.id) %></p>
      <p class="lead mb-4">Son contenu : <%= @gossip.content %> </p>
      <p class="lead mb-4">Créé le :<%= @gossip.created_at%></p>
      
    </div>
  </div>

  <div class="b-example-divider"></div>

 


    <script src="/docs/5.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>

      
  

</body>
</html>

app/views/static_pages/home.html.erb
<html>

  
  
  <body class= bg-light>
    <header>
        <div class="px-4 py-5 my-5 text-center">
          <h1 class="display-5 fw-bold">Bienvenue sur GOSSIP</h1>
            <div class="col-lg-6 mx-auto">
              <p class="lead mb-4">est-ce que tu veux des potins ?</p>
            <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
        </div>
    </header>

    <main class="container card-group">
      <% @gossips.each do |gossip| %> 
                  

        <div class="row row-cols-1 row-cols-md-2 g-4">
          <div class="col">
            <div class="card m-3 bg-white text-dark" style="width: 18rem;">
              <img src="https://img.pngio.com/gossip-podcast-gossip-png-500_500.png" class="card-img-top" alt="...">
              <div class="card-body text-center">
                <h5 class="card-title text-muted small">Gossip numéro <%= gossip.id%></h5>
                <p class="card-text ">Son titre: <%= gossip.title%></p>
                <p class="card-text text-primary small"> Son auteur : <%= gossip.user.first_name%> </p>
                <%= link_to "Lire son contenu", gossip_path(gossip), class:"btn btn-primary" %>
              </div>
            </div>
          </div>
        </div>
        
      <% end %>
    </main>

  </body>

</html>

app/views/static_pages/user_id.html.erb
<html lang="en"><head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.83.1">
    <title>Heroes · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/heroes/">

    

    <!-- Bootstrap core CSS -->
<link href="/docs/5.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#7952b3">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="heroes.css" rel="stylesheet">
  </head>
  <body>
    
<main>
  <h1 class="visually-hidden">Heroes examples</h1>

  <div class="px-4 py-5 my-5 text-center">
    <h1 class="display-5 fw-bold">Hello , voici l'utilisateurs <%= params["user_id"] %>  !</h1>
    <div class="col-lg-6 mx-auto">
      <p class="lead mb-4">Son prénom: <%= @user.first_name %> </p>
      <p class="lead mb-4">Son nom de famille: <%= @user.last_name %> </p>
      <p class="lead mb-4">Sa ville : <%= @user.city.name %> <br/></p>
      <p class="lead mb-4">Son âge : <%= @user.age %> </p>
      <p class="lead mb-4">Son email : <%= @user.email %> </p>
      

    </div>
  </div>

  <div class="b-example-divider"></div>

 


    <script src="/docs/5.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>

      
  

</body>
</html>

app/views/static_pages/welcome_user.html.erb
<h1>Hello <%= params[:id] %> ! </h1>
<p>Ici c'est notre super site de potins, il est chouette, non ?</p>